name: symhnet_env
channels:
- defaults
dependencies:
- python=3.9.7
- pandas=1.5.1
- pip
- pip:
  - numpy==1.25.0
  - keras==2.8.0
  - scikit-learn==1.3.0
  - seaborn==0.12.2
  - matplotlib==3.7.2
  - tensorflow==2.8.0
  - tensorflow-gpu==2.8.0
  - tensorboard==2.8.0  
